### ISSUE TITLE
Install dhcp client by default

### ISSUE THREAD

**Issue by kpcyrd** [Torxed/archinstall#101]
The archiso configures wired network automatically and I therefore skipped the guided network setup.

After rebooting I noticed I don't have working internet, but `$ dh<tab>` didn't yield any results. Since I don't have working internet to install a dhcp client and since I don't know the default ip range of virtualbox either I was stuck at this step. :)

I think technically systemd-networkd is installed and could do dhcp, but it's not possible to invoke it in one command without writing an actual configuration first: https://github.com/systemd/systemd/issues/14334

The archiso comes with dhclient and dhcpcd, having at least one installed (even if not configured to start automatically) would be nice.

**Comment by Torxed** [comment]
`systemd-networkd` is always installed with Arch Linux and the `systemd` package which is a part of base.
You can create your own `/etc/systemd/network/20-ethernet.network` with something like:

```
[Match]
Name=enp*
Name=eth*

[Network]
DHCP=ipv4
```
And you will have network.
This is a larger discussion - should we honor Arch Linux [KISS Principle](https://en.wikipedia.org/wiki/KISS_principle) or should we install user friendly helpers.

I would argue that during the `additional package` stage, you could simply add `dhclient dhcpcd` and you will have what you need.
But I also think, perhaps we should give a red warning text (orange if we can) to users skipping the network step, simply mentioning that Internet/Network won't automatically be enabled in the system unless these packages are added manually by the installing user.

Would that be an acceptable solution?

**Comment by kpcyrd** [comment]
I see :) How would you feel about:

```
No network configuration was selected, after reboot no network is going to be available until configured manually!
Do you want to add dhcpcd to the list of packages that should be installed? [Y/n]
```

**Comment by Torxed** [comment]
> I see :) How would you feel about:
> 
> ```
> No network configuration was selected, after reboot no network is going to be available until configured manually!
> Do you want to add dhcpcd to the list of packages that should be installed? [Y/n]
> ```

That could be a way forward, I would say that this is very non-intrusive and simply nudges the user to a informed description, so I'll consider it for the next release! I'll keep this issue open for it!

**Comment by grazzolini** [comment]
Well, dhcpcd is not the only dhcp client we have on the repos, so we could possibly add a list. Also, just installing dhcpcd doesn't mean it will get started after rebooting. As long as the user is informed, I think that's ok.
