### ISSUE TITLE
Missing range check when asked to pick an option

### ISSUE THREAD

**Issue by kpcyrd** [Torxed/archinstall#128]
The dialog asking me to pick an option by typing its number isn't checking if the choice actually exists, causing an IndexError.

Tested with 2.1.3-1

**Comment by Torxed** [comment]
> The dialog asking me to pick an option by typing its number 

You don't happen to remember which dialogue? Because most of them should have a range check.
I can go over them, they're not to many but if you recall which one - that would be very helpful :)

**Comment by Torxed** [comment]
I'll include this change in either a new patch release (v2.1.4) or if the minor release (v2.2.0) comes first.

**Comment by kpcyrd** [comment]
Nice! I think the bigger problem though is that any exception exits the program, instead there should be a loop that asks the user to try again in case of invalid input (see also #127).

I'm not sure what's the best way to do this with python (flow control with exceptions, yes/no etc), since exceptions that are "actually" unexpected exceptions shouldn't be silently discarded as invalid user input of course.
