### ISSUE TITLE
change the descriptoin of profiles

### ISSUE THREAD

**Issue by advaithm** [Torxed/archinstall#54]
all most all of the profiles use A desktop environemtn using "Awesome" window manager. even though the should be separate descriptions pertaining to the specific environment.

**Comment by Torxed** [comment]
Cheers for the report! You are correct, some comments were left untouched by mistake while setting up the three main environments I've used.

I would normally correct this pretty fast, but I'll wait for this PR from another developer who's already applied the fix in one of his branches: https://github.com/vamega/archinstall/commit/3096cdd6ff256470200ac1748a7bc34f7d05bf22#diff-598576f8241cc9e31556dfa10a42fe32b085faaaeadc9cacee4364ba0ab2da87R1
