### ISSUE TITLE
Selecting profiles require a least one profile to be given as an option

### ISSUE THREAD

**Issue by kpcyrd** [Torxed/archinstall#59]
![image](https://user-images.githubusercontent.com/7763184/97642483-2c178c00-1a3d-11eb-86a1-8a34a47776f2.png)

I got this error after following the install instructions from the readme:
```
pip install archinstall
python -m archinstall guided
```
I also accidentally booted into BIOS mode, but retrying in EFI gives me the same error.

**Comment by Torxed** [comment]
@kpcyrd That is an interesting error, it means that the profile selector could not locate any profiles. Did you configure the network properly on the machine? Or you booted straight into a pre-prepared ISO?

**Comment by kpcyrd** [comment]
The network is working correctly, I've used the regular arch iso and installed archinstall with `pip install archinstall`. :)

**Comment by Torxed** [comment]
Awesome, thank you for the feedback. Will test it out and see what the issue might be!

**Comment by Torxed** [comment]
Found the issue, it's simply a confusion in the code where `cwd` is during execution.
Trying to isolate which commit caused this issue as it has been working before. Just to be sure the fix doesn't interrupt any logic I've introduced since then : )

**Comment by Torxed** [comment]
I think that resolves it, works in the test environment at least.
If the issue still exists, I'd be happy to re-open and continue digging : )

*(pypi upload will commence shortly, with a new version release with some other fixes)*
