### ISSUE TITLE
Create PGP signed releases

### ISSUE THREAD

**Issue by grazzolini** [Torxed/archinstall#74]
Hi,

I'm creating a package of this on Arch and I would like to ask for PGP signed releases to be created. If possible, also add the keys to the release artifacts. Also, it would be a bonus if all commits **and** tags were signed. I've noticed a few of the previous tags were signed, but not the most recent ones.

Another thing that would be nice to have, is if we could build a chain of trust for all the keys that could make releasesl, not sure if one already exists.

Thanks

**Comment by Torxed** [comment]
Good idea, I'll get right on it.
I've been a tad bit lazy on the signing process, but made sure to sign the hashes of the `PKGBUILD` at the very least to make the final check verifiable.

I'll try to get this done within a day or two!

**Comment by grazzolini** [comment]
No problem. I plan on being more active on archinstall this month, and I'll try to make a few PR's to get things moving and get it into archiso next month. At least, that's my goal. It'll start with packaging archinstall. I'm thinking about making it a split package, but let's see. Also, I've discussed this with @dvzrv and we have to focus on the profiles and logging to get archinstall into archiso. Our plan is to have a separate package with a few sanctioned/vetted profiles that would also get into archiso, alongside archinstall. This would live on a separate git repository, most likely on gitlab.archlinux.org. So, this would simplify getting them into archiso, because it would mean just installing a few packages on releng profile.

**Comment by Torxed** [comment]
Just a quick update on this one, the delay is partially because I want to get my HSM to work with this in a automated and meaningful way so I can integrate it more permanently (to avoid lazy shortcuts in the future). It proved to be a bit more difficult because my very outdated hardware on the HSM hehe. So I'm waiting for an order to come through within a day or two with new hardware that supports PGP signing and stuff : ) But it's on the way!

**Comment by grazzolini** [comment]
Oh, that wasn't needed, but it's good to have! I'm going through the code now.

**Comment by Torxed** [comment]
After a bit of tinkering. Got the HSM to work flawlessly.
Commits, tags (and releases) as well as PKGBUILDS are now signed by my PGP key.

![2021-01-20-010105_200x305_scrot](https://user-images.githubusercontent.com/861439/105104787-3e8ce900-5ab3-11eb-8b0a-001892e7b499.png)

I'll add the public key used for signing in the release as an artifact :)
If there's something missing just poke a message here and I'll re-open the ticket. *(I'll have to come back to the chain of trust at some point when I'm more familiar with how that would work and the whole concept)*.

**Comment by kpcyrd** [comment]
Please sign the tarball generated with:
```
git archive --prefix="archinstall-2.1.0/" -o ./archinstall-2.1.0.tar.gz "v2.1.0"
```
instead of just the commit and attach the signature to the release. :)

**Comment by grazzolini** [comment]
Thanks! Also thanks @kpcyrd, I was going to mention the lack of signatures on the artifacts as well.

**Comment by Torxed** [comment]
@kpcyrd @grazzolini Thank you both, this is honestly my first time signing things from the command-line, I've usually done everything via the GitHub GUI over the years. It's been a long time coming and I was bound to do some mistakes, so thank you for the help.

Key has been uploaded to https://keys.openpgp.org/search?q=256F73CEEFC6705C6BBAB20E5FBBB32941E3740A as well as a signature of the tarball is now attached to the release on the release page. I hope I didn't get that wrong or missed anything.

**Comment by grazzolini** [comment]
So far it's looking ok to me. I'll try creating packges today, let's see.

**Comment by Torxed** [comment]
@grazzolini Awesome, looking forward to it :) Let me know if you find anything, I've been installing some 20 machines today just to verify as much as possible, and it's looking good. I'll avoid major changes for a bit and work only on the logging feature #56.

**Comment by grazzolini** [comment]
Yes, #56 should probably be done before putting this into archiso.

**Comment by grazzolini** [comment]
archisntall is now on the official repos: https://archlinux.org/packages/?q=archinstall

**Comment by Torxed** [comment]
This terrifies me, but at the same time I'm super excited hehe :)
