### ISSUE TITLE
Create man pages

### ISSUE THREAD

**Issue by grazzolini** [Torxed/archinstall#78]
Now that archinstall is packaged on the official repos, it would be nice to have man pages for it as well. I think that, with some adaptation, they could be created from the docutils documentation.

**Comment by Torxed** [comment]
Great Idea, saw today that https://man.archlinux.org/ has been set up and working, looks great.
I've prepared some docstrings but that has to be thurrowly adapted throughout the code, will most likely be the weekend project.

I'll update both the [docs/](docs/) as well as docstrings and look into how to properly create a man page for it!

**Comment by grazzolini** [comment]
I opened the issue, but I was already looking into manpage writer for docutils. Thing is, since this would introduce a lot of changes, wanted to create the issue first for the discussion. But glad to know you already had that in mind too.

**Comment by Torxed** [comment]
The current `docs/` support creating man pages through `make man` *(using sphinx)*.
It's not the most pretty thing, and perhaps I need to update the make-depends to add:
 * python-sphinx
 * python-sphinx_rtd_theme
And add a additional "build docs" / man-pages?
Or should I upload it as an artifact to each release?

I'm currently re-working the structure of the `.rst`-files to look better in `man archinstall`.
Currently the layout doesn't make much sense :)

**Comment by grazzolini** [comment]
I think that creating man pages should be part of setup.py. If we need to add a makedep on sphinx, it's not an issue.

**Comment by Torxed** [comment]
Man pages now look a bit neater.
They can be built and verified by doing the following:

```
$ cd docs/
$ make man
$ sudo cp _build/man/archinstall.1 /usr/share/man/man1/
$ man archinstall
```

And it should look something like the following:
![2021-01-26-144558_1611x1335_scrot](https://user-images.githubusercontent.com/861439/105852982-7630ef00-5fe5-11eb-9486-bab9a99306dc.png)
