### ISSUE TITLE
Crashes upon trying to skip picking an environment after desktop

### ISSUE THREAD

**Issue by j-james** [Torxed/archinstall#86]
When prompted by the installer script to select a pre-programmed profile, selecting option 1 (desktop) and then trying to skip by pressing enter crashes the installer.

**Comment by Torxed** [comment]
Think the main reason for this is that the installer doesn't have a "known state" it can jump back to if you opt to "go out" from a sub-selection without completing the track selected. This is probably a bit counter-intuitive.

Perhaps a Ctrl-C or "back" function would be handy, I'll think about it for a bit.
